# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_draft', '0003_auto_20160105_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bid',
            field=models.IntegerField(default=0),
        ),
    ]
