# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 09:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_draft', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='players',
            field=models.ManyToManyField(blank=True, to='fantasy_draft.Player'),
        ),
        migrations.AlterField(
            model_name='league',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='player',
            name='tournaments',
            field=models.ManyToManyField(blank=True, to='fantasy_draft.Tournament'),
        ),
    ]
