# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 03:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_draft', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
