# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_draft', '0003_auto_20151231_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy_draft.Tournament'),
        ),
    ]
