# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_draft', '0004_auto_20160105_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='ascending',
            field=models.BooleanField(default=True),
        ),
    ]
