# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 09:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_draft', '0004_auto_20151231_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issued', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('UNA', 'unanswered'), ('ACC', 'accepted'), ('DEC', 'declined')], default='UNA', max_length=3)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy_draft.League')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy_draft.Tournament')),
            ],
        ),
    ]
