# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 09:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_draft', '0005_invitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='tournament',
        ),
    ]
