# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_draft', '0007_auto_20160101_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
