# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 11:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_draft', '0008_league_started'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league',
            old_name='started',
            new_name='activated',
        ),
    ]
