# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_draft', '0009_auto_20160101_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='date_created',
            field=models.DateTimeField(),
        ),
    ]
