# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_draft', '0010_auto_20160101_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='num_picks',
            field=models.PositiveSmallIntegerField(default=5),
            preserve_default=False,
        ),
    ]
