# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 22:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_draft', '0011_league_num_picks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league',
            old_name='num_picks',
            new_name='number_of_picks',
        ),
    ]
