# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_draft', '0012_auto_20160101_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='activated',
        ),
        migrations.AddField(
            model_name='league',
            name='phase',
            field=models.CharField(choices=[('P', 'Phase 1: Preliminary'), ('A', 'Phase 2: Active'), ('C', 'Phase 3: Complete')], default='P', max_length=1),
        ),
    ]
