# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_draft', '0013_auto_20160101_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='phase',
            field=models.CharField(choices=[('PRE', 'Phase 1: Preliminary'), ('ACT', 'Phase 2: Active'), ('COM', 'Phase 3: Complete')], default='PRE', max_length=3),
        ),
    ]
