# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_draft', '0014_auto_20160101_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='random_order',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='league',
            name='snake_style',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='league',
            name='phase',
            field=models.CharField(choices=[('PRE', 'Phase 1: Preliminary'), ('BID', 'Phase 2: Bidding'), ('SEL', 'Phase 3: Selection'), ('COM', 'Phase 4: Complete')], default='PRE', max_length=3),
        ),
    ]
