# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_draft', '0015_auto_20160101_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='random_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='league',
            name='snake_style',
            field=models.BooleanField(default=False),
        ),
    ]
